spring.application.name=project management system

server.address=0.0.0.0
server.port=5454

spring.datasource.url=jdbc:mysql://localhost:3306/projectmanagement
spring.datasource.username=root
spring.datasource.password=loq@ryzen7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aryandaksh2711@gmail.com
spring.mail.password=uwnl pqty ndxd oekq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.api.key=rzp_live_hnnwOj35oHpWqs
razorpay.api.secret=H5bBxf8Tn1Ex2cun1G7pVdKN